#!/usr/bin/env perl

use strict;
use warnings;
use 5.014;
use Net::Pcap qw(:functions);

our $VERSION = '0.00';

sub process_packet {
	my ($user_data, $header, $packet) = @_;

	my ($id, $type, $transtype, $endpoint, $device, $busid, $req,
	$dataflag, $sec, $usec, $status, $length, $datalength,
	$direction, $bmtype, $bmrecip, $breq, $wvalue, $windex, $wlen, $data)
		= unpack("H16 c c H2 C S H2 H2 H16 H8 H8 H8 H8 B B2 B5 C S S S H*", $packet);

	printf("     ID %s\n  type %c\n ttype %d\n", $id, $type, $transtype);
	printf("    ep %02x\n   dev %s\n busid %d\n", $endpoint, $device, $busid);
	printf("  sreq %s\n data? %s\nstatus %s\n", $req, $dataflag, $status);
	printf("   len %s\n  dlen %s\n", $length, $datalength);
	printf("   dir %d\nbmtype %d\nbmreci %d\n", $direction, $bmtype, $bmrecip);
	printf("  breq %d\nwvalue %d\nwindex %d\n", $breq, $wvalue, $windex);
	printf("  wlen %d\n  data %s\n\n", $wlen || 0, $data // q{});

#	say unpack("W*", $packet);
}

my $err;
my $pcap = pcap_open_offline('ds1m12', \$err);

pcap_loop($pcap, -1, \&process_packet, undef);

pcap_close($pcap);

__END__

=head1 NAME

=head1 SYNOPSIS

=head1 VERSION

=head1 DESCRIPTION

=head1 OPTIONS

=over

=back

=head1 EXIT STATUS

=head1 CONFIGURATION

None.

=head1 DEPENDENCIES

=over

=back

=head1 BUGS AND LIMITATIONS

=head1 AUTHOR

Copyright (C) 2013 by Daniel Friesel E<lt>derf@finalrewind.orgE<gt>

=head1 LICENSE

  0. You just DO WHAT THE FUCK YOU WANT TO.
